package com.manjano.bus.models

// Complete country list
object CountryRepository {
    val countries = listOf(
        Country("🇰🇪", "+254", "Kenya", "KE", "254"), //Default
        Country("🇦🇫", "+93", "Afghanistan", "AF", "93"),
        Country("🇦🇱", "+355", "Albania", "AL", "355"),
        Country("🇩🇿", "+213", "Algeria", "DZ", "213"),
        Country("🇦🇸", "+1684", "American Samoa", "AS", "1684"),
        Country("🇦🇩", "+376", "Andorra", "AD", "376"),
        Country("🇦🇴", "+244", "Angola", "AO", "244"),
        Country("🇦🇮", "+1264", "Anguilla", "AI", "1264"),
        Country("🇦🇬", "+1268", "Antigua and Barbuda", "AG", "1268"),
        Country("🇦🇷", "+54", "Argentina", "AR", "54"),
        Country("🇦🇲", "+374", "Armenia", "AM", "374"),
        Country("🇦🇼", "+297", "Aruba", "AW", "297"),
        Country("🇦🇺", "+61", "Australia", "AU", "61"),
        Country("🇦🇹", "+43", "Austria", "AT", "43"),
        Country("🇦🇿", "+994", "Azerbaijan", "AZ", "994"),
        Country("🇧🇸", "+1242", "Bahamas", "BS", "1242"),
        Country("🇧🇭", "+973", "Bahrain", "BH", "973"),
        Country("🇧🇩", "+880", "Bangladesh", "BD", "880"),
        Country("🇧🇧", "+1246", "Barbados", "BB", "1246"),
        Country("🇧🇾", "+375", "Belarus", "BY", "375"),
        Country("🇧🇪", "+32", "Belgium", "BE", "32"),
        Country("🇧🇿", "+501", "Belize", "BZ", "501"),
        Country("🇧🇯", "+229", "Benin", "BJ", "229"),
        Country("🇧🇲", "+1441", "Bermuda", "BM", "1441"),
        Country("🇧🇹", "+975", "Bhutan", "BT", "975"),
        Country("🇧🇴", "+591", "Bolivia", "BO", "591"),
        Country("🇧🇦", "+387", "Bosnia and Herzegovina", "BA", "387"),
        Country("🇧🇼", "+267", "Botswana", "BW", "267"),
        Country("🇧🇷", "+55", "Brazil", "BR", "55"),
        Country("🇮🇴", "+246", "British Indian Ocean Territory", "IO", "246"),
        Country("🇻🇬", "+1284", "British Virgin Islands", "VG", "1284"),
        Country("🇧🇳", "+673", "Brunei", "BN", "673"),
        Country("🇧🇬", "+359", "Bulgaria", "BG", "359"),
        Country("🇧🇫", "+226", "Burkina Faso", "BF", "226"),
        Country("🇧🇮", "+257", "Burundi", "BI", "257"),
        Country("🇰🇭", "+855", "Cambodia", "KH", "855"),
        Country("🇨🇲", "+237", "Cameroon", "CM", "237"),
        Country("🇨🇦", "+1", "Canada", "CA", "1"),
        Country("🇨🇻", "+238", "Cape Verde", "CV", "238"),
        Country("🇧🇶", "+599", "Caribbean Netherlands", "BQ", "599"),
        Country("🇰🇾", "+1345", "Cayman Islands", "KY", "1345"),
        Country("🇨🇫", "+236", "Central African Republic", "CF", "236"),
        Country("🇹🇩", "+235", "Chad", "TD", "235"),
        Country("🇨🇱", "+56", "Chile", "CL", "56"),
        Country("🇨🇳", "+86", "China", "CN", "86"),
        Country("🇨🇽", "+61", "Christmas Island", "CX", "61"),
        Country("🇨🇨", "+61", "Cocos (Keeling) Islands", "CC", "61"),
        Country("🇨🇴", "+57", "Colombia", "CO", "57"),
        Country("🇰🇲", "+269", "Comoros", "KM", "269"),
        Country("🇨🇬", "+242", "Congo - Brazzaville", "CG", "242"),
        Country("🇨🇩", "+243", "Congo - Kinshasa", "CD", "243"),
        Country("🇨🇷", "+506", "Costa Rica", "CR", "506"),
        Country("🇭🇷", "+385", "Croatia", "HR", "385"),
        Country("🇨🇺", "+53", "Cuba", "CU", "53"),
        Country("🇨🇾", "+357", "Cyprus", "CY", "357"),
        Country("🇨🇿", "+420", "Czechia", "CZ", "420"),
        Country("🇩🇰", "+45", "Denmark", "DK", "45"),
        Country("🇩🇯", "+253", "Djibouti", "DJ", "253"),
        Country("🇩🇲", "+1767", "Dominica", "DM", "1767"),
        Country("🇩🇴", "+1809", "Dominican Republic", "DO", "1809"),
        Country("🇪🇨", "+593", "Ecuador", "EC", "593"),
        Country("🇪🇬", "+20", "Egypt", "EG", "20"),
        Country("🇸🇻", "+503", "El Salvador", "SV", "503"),
        Country("🇬🇶", "+240", "Equatorial Guinea", "GQ", "240"),
        Country("🇪🇷", "+291", "Eritrea", "ER", "291"),
        Country("🇪🇪", "+372", "Estonia", "EE", "372"),
        Country("🇸🇿", "+268", "Eswatini", "SZ", "268"),
        Country("🇪🇹", "+251", "Ethiopia", "ET", "251"),
        Country("🇫🇯", "+679", "Fiji", "FJ", "679"),
        Country("🇫🇮", "+358", "Finland", "FI", "358"),
        Country("🇫🇷", "+33", "France", "FR", "33"),
        Country("🇬🇦", "+241", "Gabon", "GA", "241"),
        Country("🇬🇲", "+220", "Gambia", "GM", "220"),
        Country("🇬🇪", "+995", "Georgia", "GE", "995"),
        Country("🇩🇪", "+49", "Germany", "DE", "49"),
        Country("🇬🇭", "+233", "Ghana", "GH", "233"),
        Country("🇬🇷", "+30", "Greece", "GR", "30"),
        Country("🇬🇩", "+1473", "Grenada", "GD", "1473"),
        Country("🇬🇹", "+502", "Guatemala", "GT", "502"),
        Country("🇬🇳", "+224", "Guinea", "GN", "224"),
        Country("🇬🇼", "+245", "Guinea-Bissau", "GW", "245"),
        Country("🇬🇾", "+592", "Guyana", "GY", "592"),
        Country("🇭🇹", "+509", "Haiti", "HT", "509"),
        Country("🇭🇳", "+504", "Honduras", "HN", "504"),
        Country("🇭🇺", "+36", "Hungary", "HU", "36"),
        Country("🇮🇸", "+354", "Iceland", "IS", "354"),
        Country("🇮🇳", "+91", "India", "IN", "91"),
        Country("🇮🇩", "+62", "Indonesia", "ID", "62"),
        Country("🇮🇷", "+98", "Iran", "IR", "98"),
        Country("🇮🇶", "+964", "Iraq", "IQ", "964"),
        Country("🇮🇪", "+353", "Ireland", "IE", "353"),
        Country("🇮🇱", "+972", "Israel", "IL", "972"),
        Country("🇮🇹", "+39", "Italy", "IT", "39"),
        Country("🇨🇮", "+225", "Ivory Coast", "CI", "225"),
        Country("🇯🇲", "+1876", "Jamaica", "JM", "1876"),
        Country("🇯🇵", "+81", "Japan", "JP", "81"),
        Country("🇯🇴", "+962", "Jordan", "JO", "962"),
        Country("🇰🇿", "+7", "Kazakhstan", "KZ", "7"),
        Country("🇰🇪", "+254", "Kenya", "KE", "254"),
        Country("🇰🇮", "+686", "Kiribati", "KI", "686"),
        Country("🇽🇰", "+383", "Kosovo", "XK", "383"),
        Country("🇰🇼", "+965", "Kuwait", "KW", "965"),
        Country("🇰🇬", "+996", "Kyrgyzstan", "KG", "996"),
        Country("🇱🇦", "+856", "Laos", "LA", "856"),
        Country("🇱🇻", "+371", "Latvia", "LV", "371"),
        Country("🇱🇧", "+961", "Lebanon", "LB", "961"),
        Country("🇱🇸", "+266", "Lesotho", "LS", "266"),
        Country("🇱🇷", "+231", "Liberia", "LR", "231"),
        Country("🇱🇾", "+218", "Libya", "LY", "218"),
        Country("🇱🇮", "+423", "Liechtenstein", "LI", "423"),
        Country("🇱🇹", "+370", "Lithuania", "LT", "370"),
        Country("🇱🇺", "+352", "Luxembourg", "LU", "352"),
        Country("🇲🇬", "+261", "Madagascar", "MG", "261"),
        Country("🇲🇼", "+265", "Malawi", "MW", "265"),
        Country("🇲🇾", "+60", "Malaysia", "MY", "60"),
        Country("🇲🇻", "+960", "Maldives", "MV", "960"),
        Country("🇲🇱", "+223", "Mali", "ML", "223"),
        Country("🇲🇹", "+356", "Malta", "MT", "356"),
        Country("🇲🇭", "+692", "Marshall Islands", "MH", "692"),
        Country("🇲🇷", "+222", "Mauritania", "MR", "222"),
        Country("🇲🇺", "+230", "Mauritius", "MU", "230"),
        Country("🇲🇽", "+52", "Mexico", "MX", "52"),
        Country("🇫🇲", "+691", "Micronesia", "FM", "691"),
        Country("🇲🇩", "+373", "Moldova", "MD", "373"),
        Country("🇲🇨", "+377", "Monaco", "MC", "377"),
        Country("🇲🇳", "+976", "Mongolia", "MN", "976"),
        Country("🇲🇪", "+382", "Montenegro", "ME", "382"),
        Country("🇲🇸", "+1664", "Montserrat", "MS", "1664"),
        Country("🇲🇦", "+212", "Morocco", "MA", "212"),
        Country("🇲🇿", "+258", "Mozambique", "MZ", "258"),
        Country("🇲🇲", "+95", "Myanmar", "MM", "95"),
        Country("🇳🇦", "+264", "Namibia", "NA", "264"),
        Country("🇳🇷", "+674", "Nauru", "NR", "674"),
        Country("🇳🇵", "+977", "Nepal", "NP", "977"),
        Country("🇳🇱", "+31", "Netherlands", "NL", "31"),
        Country("🇳🇨", "+687", "New Caledonia", "NC", "687"),
        Country("🇳🇿", "+64", "New Zealand", "NZ", "64"),
        Country("🇳🇮", "+505", "Nicaragua", "NI", "505"),
        Country("🇳🇪", "+227", "Niger", "NE", "227"),
        Country("🇳🇬", "+234", "Nigeria", "NG", "234"),
        Country("🇳🇺", "+683", "Niue", "NU", "683"),
        Country("🇰🇵", "+850", "North Korea", "KP", "850"),
        Country("🇲🇰", "+389", "North Macedonia", "MK", "389"),
        Country("🇳🇴", "+47", "Norway", "NO", "47"),
        Country("🇴🇲", "+968", "Oman", "OM", "968"),
        Country("🇵🇰", "+92", "Pakistan", "PK", "92"),
        Country("🇵🇼", "+680", "Palau", "PW", "680"),
        Country("🇵🇸", "+970", "Palestine", "PS", "970"),
        Country("🇵🇦", "+507", "Panama", "PA", "507"),
        Country("🇵🇬", "+675", "Papua New Guinea", "PG", "675"),
        Country("🇵🇾", "+595", "Paraguay", "PY", "595"),
        Country("🇵🇪", "+51", "Peru", "PE", "51"),
        Country("🇵🇭", "+63", "Philippines", "PH", "63"),
        Country("🇵🇱", "+48", "Poland", "PL", "48"),
        Country("🇵🇹", "+351", "Portugal", "PT", "351"),
        Country("🇵🇷", "+1787", "Puerto Rico", "PR", "1787"),
        Country("🇶🇦", "+974", "Qatar", "QA", "974"),
        Country("🇷🇴", "+40", "Romania", "RO", "40"),
        Country("🇷🇺", "+7", "Russia", "RU", "7"),
        Country("🇷🇼", "+250", "Rwanda", "RW", "250"),
        Country("🇼🇸", "+685", "Samoa", "WS", "685"),
        Country("🇸🇲", "+378", "San Marino", "SM", "378"),
        Country("🇸🇹", "+239", "São Tomé and Príncipe", "ST", "239"),
        Country("🇸🇦", "+966", "Saudi Arabia", "SA", "966"),
        Country("🇸🇳", "+221", "Senegal", "SN", "221"),
        Country("🇷🇸", "+381", "Serbia", "RS", "381"),
        Country("🇸🇨", "+248", "Seychelles", "SC", "248"),
        Country("🇸🇱", "+232", "Sierra Leone", "SL", "232"),
        Country("🇸🇬", "+65", "Singapore", "SG", "65"),
        Country("🇸🇰", "+421", "Slovakia", "SK", "421"),
        Country("🇸🇮", "+386", "Slovenia", "SI", "386"),
        Country("🇸🇧", "+677", "Solomon Islands", "SB", "677"),
        Country("🇸🇴", "+252", "Somalia", "SO", "252"),
        Country("🇿🇦", "+27", "South Africa", "ZA", "27"),
        Country("🇰🇷", "+82", "South Korea", "KR", "82"),
        Country("🇸🇸", "+211", "South Sudan", "SS", "211"),
        Country("🇪🇸", "+34", "Spain", "ES", "34"),
        Country("🇱🇰", "+94", "Sri Lanka", "LK", "94"),
        Country("🇸🇩", "+249", "Sudan", "SD", "249"),
        Country("🇸🇷", "+597", "Suriname", "SR", "597"),
        Country("🇸🇪", "+46", "Sweden", "SE", "46"),
        Country("🇨🇭", "+41", "Switzerland", "CH", "41"),
        Country("🇸🇾", "+963", "Syria", "SY", "963"),
        Country("🇹🇼", "+886", "Taiwan", "TW", "886"),
        Country("🇹🇯", "+992", "Tajikistan", "TJ", "992"),
        Country("🇹🇿", "+255", "Tanzania", "TZ", "255"),
        Country("🇹🇭", "+66", "Thailand", "TH", "66"),
        Country("🇹🇱", "+670", "Timor-Leste", "TL", "670"),
        Country("🇹🇬", "+228", "Togo", "TG", "228"),
        Country("🇹🇴", "+676", "Tonga", "TO", "676"),
        Country("🇹🇹", "+1868", "Trinidad and Tobago", "TT", "1868"),
        Country("🇹🇳", "+216", "Tunisia", "TN", "216"),
        Country("🇹🇷", "+90", "Turkey", "TR", "90"),
        Country("🇹🇲", "+993", "Turkmenistan", "TM", "993"),
        Country("🇹🇨", "+1649", "Turks and Caicos Islands", "TC", "1649"),
        Country("🇹🇻", "+688", "Tuvalu", "TV", "688"),
        Country("🇺🇬", "+256", "Uganda", "UG", "256"),
        Country("🇺🇦", "+380", "Ukraine", "UA", "380"),
        Country("🇦🇪", "+971", "United Arab Emirates", "AE", "971"),
        Country("🇬🇧", "+44", "United Kingdom", "GB", "44"),
        Country("🇺🇸", "+1", "United States", "US", "1"),
        Country("🇺🇾", "+598", "Uruguay", "UY", "598"),
        Country("🇺🇿", "+998", "Uzbekistan", "UZ", "998"),
        Country("🇻🇺", "+678", "Vanuatu", "VU", "678"),
        Country("🇻🇦", "+379", "Vatican City", "VA", "379"),
        Country("🇻🇪", "+58", "Venezuela", "VE", "58"),
        Country("🇻🇳", "+84", "Vietnam", "VN", "84"),
        Country("🇾🇪", "+967", "Yemen", "YE", "967"),
        Country("🇿🇲", "+260", "Zambia", "ZM", "260"),
        Country("🇿🇼", "+263", "Zimbabwe", "ZW", "263")
    )

    fun getDefaultCountry(): Country = countries.first()
}
